theme = "tokyonight_moon"

[editor]
mouse = false
completion-trigger-len = 4
completion-replace = true
text-width = 80
rulers = [81]
trim-trailing-whitespace = true
popup-border = "menu"
clipboard-provider = "wayland"
jump-label-alphabet = "qawsedgrftcx"

[editor.inline-diagnostics]
cursor-line = "warning"
prefix-len = 2
max-diagnostics = 20

[editor.gutters]
layout = ["spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 1
character = "⸽"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[editor.statusline]
left = ["mode", "version-control", "file-name", "file-modification-indicator"]
center = []
right = ["workspace-diagnostics", "diagnostics", "selections", "primary-selection-length", "position", "spinner"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
f = {j = ["normal_mode", ":write"], k = ["normal_mode", ":wq"], h = ["normal_mode", ":quit"]}

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
